# This file was generated by GoReleaser. DO NOT EDIT.
cask "bastion" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "3ad142c6acbdce8e418bbe44418e715e414c9ea0f575d0dfa611e9a3f877d11b"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8e659918a2a35aebc7cdd7465ef8a57ef999b82570d8fe4711e1886a22356194"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "de657e80a256685aadb126faf0064e6a97b52e5cc923dabbfc4309bab4c60cf5"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "71bea964c050a29b20e6fd77cae3c9e582d1fcf5b845a7d0018a7afe96124d67"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bastion"
  desc "Config-driven CLI for operating a personal dev box on GCE"
  homepage "https://github.com/sanketsaurav/bastion"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bastion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bastion"]
    end
  end

  # No zap stanza required
end
