# This file was generated by GoReleaser. DO NOT EDIT.
cask "bastion" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "0510a1c4275a0136fd6bf33e36f9b4e88292344fd64b5a763fe8f57be99316ac"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7618e20d484b0a0accfa82b11646adefec25753c8e778a6b8ed10beb30d0aec4"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bfccefc57321e54f42a19a5fab4770ae895b6fa26b001ccbb2352ca5f880b305"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "be7b40ed8f070479bcab4045a0f22a6f9b07e716ebf23f39b9aeb21c629f6098"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bastion"
  desc "Config-driven CLI for operating a personal dev box on GCE"
  homepage "https://github.com/sanketsaurav/bastion"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bastion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bastion"]
    end
  end

  # No zap stanza required
end
