# This file was generated by GoReleaser. DO NOT EDIT.
cask "bastion" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "45390d5d313c680616849721f49ff5a6edb167fcb4eacc6dbb322bcd905ad067"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0129a4dc55a05130c44bf65bb70cd1a4e8841cd268e954669a2a321bfb95f966"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c5cd65d2a7e9ac6896607181753c9059b3250c275e839eacf6d58c60f5a6eb2c"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0e6db191f11465bf555c0bf03cf004fb2539e249ad06b50451d019df49a8d38"
      url "https://github.com/sanketsaurav/bastion/releases/download/v#{version}/bastion_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bastion"
  desc "Config-driven CLI for operating a personal dev box on GCE"
  homepage "https://github.com/sanketsaurav/bastion"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bastion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bastion"]
    end
  end

  # No zap stanza required
end
