# This file is regenerated by portia's release workflow on every tagged
# release (version + sha256 are filled in automatically). Don't edit by hand.
cask "portia" do
  version "0.5.2"
  sha256 "8b25cc89318026daca9abbd55a72be8e993031f63ab4856a568a7bd43d7e164b"

  url "https://dl.portia.sh/v0.5.2/Portia-0.5.2.dmg"
  name "Portia"
  desc "Local, web-based code review built for AI coding agents"
  homepage "https://portia.sh"

  depends_on macos: :monterey

  app "Portia.app"

  zap trash: [
    "~/Library/Caches/com.portia.app",
    "~/Library/Caches/Portia",
    "~/Library/Application Support/Portia",
    "~/Library/Preferences/com.portia.app.plist",
    "~/Library/Saved Application State/com.portia.app.savedState",
  ]
end
