# This file is regenerated by portia's release workflow on every tagged
# release (version + sha256 are filled in automatically). Don't edit by hand.
cask "portia" do
  version "0.8.0"
  sha256 "b5ef9fc52955e660c22a2a6441753788e78f6230d596b3c8ab98e1f1bc7deb6b"

  url "https://dl.portia.sh/v0.8.0/Portia-0.8.0.dmg"
  name "Portia"
  desc "Local, web-based code review built for AI coding agents"
  homepage "https://portia.sh"

  depends_on macos: :monterey

  app "Portia.app"

  zap trash: [
    "~/Library/Caches/com.portia.app",
    "~/Library/Caches/Portia",
    "~/Library/Application Support/Portia",
    "~/Library/Preferences/com.portia.app.plist",
    "~/Library/Saved Application State/com.portia.app.savedState",
  ]
end
