# This file is regenerated by portia's release workflow on every tagged
# release (version + sha256 are filled in automatically). Don't edit by hand.
cask "portia" do
  version "0.11.0"
  sha256 "4e875ab84cef59ca93a1d670d1c052b027697edb63210bb646650a1a6e3d92a7"

  url "https://dl.portia.sh/v0.11.0/Portia-0.11.0.dmg"
  name "Portia"
  desc "Local, web-based code review built for AI coding agents"
  homepage "https://portia.sh"

  depends_on macos: :monterey

  app "Portia.app"

  zap trash: [
    "~/Library/Caches/com.portia.app",
    "~/Library/Caches/Portia",
    "~/Library/Application Support/Portia",
    "~/Library/Preferences/com.portia.app.plist",
    "~/Library/Saved Application State/com.portia.app.savedState",
  ]
end
