# This file is regenerated by portia's release workflow on every tagged
# release (version + sha256s are filled in automatically). Don't edit by hand.
class Portia < Formula
  desc "Local, web-based code review built for AI coding agents"
  homepage "https://portia.sh"
  version "0.9.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://dl.portia.sh/v0.9.1/portia-darwin-arm64"
      sha256 "57d5e70a3344eb57f865373ed3a0d4abeb9094497ef0e1493d5b40da85d862fe"
    end
    on_intel do
      url "https://dl.portia.sh/v0.9.1/portia-darwin-x64"
      sha256 "4ac80e781e8ac96c89da1deff389aa9fa9f163ef83d4582563755f35302b2e3e"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.portia.sh/v0.9.1/portia-linux-arm64"
      sha256 "684bf16bc7b2f37913e93bc19098e6de6ed59db9f4bd27d963e11db34362e39a"
    end
    on_intel do
      url "https://dl.portia.sh/v0.9.1/portia-linux-x64"
      sha256 "1ac429dd071a70363498017c876ba7ce8e00be9d10d3cd96e7dd8e23887d748a"
    end
  end

  def install
    bin.install Dir["portia-*"].first => "portia"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/portia --version")
  end
end
