# This file is regenerated by portia's release workflow on every tagged
# release (version + sha256s are filled in automatically). Don't edit by hand.
class Portia < Formula
  desc "Local, web-based code review built for AI coding agents"
  homepage "https://portia.sh"
  version "0.7.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://dl.portia.sh/v0.7.0/portia-darwin-arm64"
      sha256 "0e25a7a70ca479dd1f8cd14e32b62044b6fd3afb05e0bb1076c7a1385290f97c"
    end
    on_intel do
      url "https://dl.portia.sh/v0.7.0/portia-darwin-x64"
      sha256 "19886a13e89506a61739a820e801781c268165f956cb1210d5f86aa036c8321a"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.portia.sh/v0.7.0/portia-linux-arm64"
      sha256 "51397b239eb43f9c53507f0af950c4a8a50478ba764b0040d205e0e7d7d9d9f8"
    end
    on_intel do
      url "https://dl.portia.sh/v0.7.0/portia-linux-x64"
      sha256 "c8bd6ee5554d4ce4d9307818a6707c2130eba12a6b373800e81cb9a168ff4fd7"
    end
  end

  def install
    bin.install Dir["portia-*"].first => "portia"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/portia --version")
  end
end
