# This file is regenerated by portia's release workflow on every tagged
# release (version + sha256s are filled in automatically). Don't edit by hand.
class Portia < Formula
  desc "Local, web-based code review built for AI coding agents"
  homepage "https://portia.sh"
  version "0.11.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://dl.portia.sh/v0.11.0/portia-darwin-arm64"
      sha256 "79e2d478d653e5ff9b4132c4f2055e1000b35198e216fe1a738aa18aba884376"
    end
    on_intel do
      url "https://dl.portia.sh/v0.11.0/portia-darwin-x64"
      sha256 "a63ac0e3e655ef271605a46a276758a9f04ddb78ee927afafec9bc432a238452"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.portia.sh/v0.11.0/portia-linux-arm64"
      sha256 "25e5488233284cfbdb937156bde3414337d4bccb328623838b222d9d31c91a9c"
    end
    on_intel do
      url "https://dl.portia.sh/v0.11.0/portia-linux-x64"
      sha256 "c14c3b56cba4e32871efa92bd3c89562c5dcb7c56a46095f6e1c968eda79ed23"
    end
  end

  def install
    bin.install Dir["portia-*"].first => "portia"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/portia --version")
  end
end
